import type { Email, Reminder } from './types'
export const emails:Email[]=[
{id:'e1',sender:'Sarah Chen',email:'sarah@northstar.io',initials:'SC',subject:'Interview availability — final round',preview:'We would love to invite you to the final technical interview. Would Monday or Tuesday work?',body:'Hi Aditya,\n\nGreat news — the team enjoyed your technical interview and we would love to invite you to the final round. We can offer Monday at 11:00 AM or Tuesday at 3:00 PM. Please confirm your preferred time by tomorrow.\n\nI have attached our interview preparation guide.\n\nBest,\nSarah',receivedAt:'Today, 9:42 AM',relativeTime:'12m',category:'Urgent',priority:96,unread:true,starred:true,summary:'Northstar has invited you to a final interview. Choose Monday at 11:00 AM or Tuesday at 3:00 PM and confirm by tomorrow.',actionRequired:'Choose an interview time and reply',reason:'Direct response requested within 24 hours',people:['Sarah Chen','Aditya'],attachments:['Interview preparation guide.pdf'],actionItems:[{task:'Confirm preferred interview time',deadline:'Tomorrow',owner:'You'}],threadCount:3},
{id:'e2',sender:'Marcus Liu',email:'marcus@atlasdesign.co',initials:'ML',subject:'Re: Brand system — final revisions',preview:'The new direction looks strong. There are three small changes before we can approve the delivery.',body:'Hey Aditya,\n\nThe new direction looks strong. Before approval, could you update the mobile wordmark, increase contrast on the secondary palette, and export the icon set as SVG? Friday EOD works for us.\n\nThanks,\nMarcus',receivedAt:'Today, 8:18 AM',relativeTime:'1h',category:'Requires reply',priority:84,unread:true,starred:false,summary:'Atlas Design likes the new brand direction and requested three final revisions before Friday EOD.',actionRequired:'Acknowledge and complete three revisions',reason:'Multiple deliverables with a near-term deadline',people:['Marcus Liu','Aditya'],attachments:[],actionItems:[{task:'Update mobile wordmark',deadline:'Friday EOD',owner:'You'},{task:'Increase secondary palette contrast',deadline:'Friday EOD',owner:'You'},{task:'Export icon set as SVG',deadline:'Friday EOD',owner:'You'}],threadCount:8},
{id:'e3',sender:'Stripe',email:'notifications@stripe.com',initials:'ST',subject:'Invoice #1048 was paid',preview:'Your payment of $2,400.00 from Halcyon Labs has completed successfully.',body:'Your payment of $2,400.00 USD from Halcyon Labs has completed successfully. Funds will arrive in your bank account on August 11, 2026.',receivedAt:'Yesterday, 6:04 PM',relativeTime:'15h',category:'Invoice',priority:42,unread:false,starred:false,summary:'A $2,400 payment from Halcyon Labs completed and is expected in your bank account August 11.',actionRequired:'No action required',reason:'Informational payment confirmation',people:['Stripe','Halcyon Labs'],attachments:['Receipt-1048.pdf'],actionItems:[],threadCount:1},
{id:'e4',sender:'Maya Rodriguez',email:'maya@fieldnotes.fm',initials:'MR',subject:'Podcast collaboration next month?',preview:'I have been following your work and would love to have you on the show next month.',body:'Hi Aditya,\n\nI have been following your work on practical AI products and would love to have you on Field Notes next month. Would you be open to a 30-minute call next week to discuss the format?\n\nWarmly,\nMaya',receivedAt:'Yesterday, 2:31 PM',relativeTime:'19h',category:'Meeting',priority:71,unread:false,starred:true,summary:'Maya invited you onto the Field Notes podcast and proposed a 30-minute planning call next week.',actionRequired:'Decide whether to accept and offer availability',reason:'Personal invitation requiring a scheduling response',people:['Maya Rodriguez','Aditya'],attachments:[],actionItems:[{task:'Reply with availability for a planning call',deadline:'This week',owner:'You'}],threadCount:1},
{id:'e5',sender:'Noah Williams',email:'noah@kinetic.dev',initials:'NW',subject:'Checking in on the API proposal',preview:'Just checking whether you had a chance to review the scope I sent over last week.',body:'Hi Aditya,\n\nJust checking whether you had a chance to review the API integration scope I sent over last week. Happy to answer any questions or adjust the milestones.\n\nBest,\nNoah',receivedAt:'Mon, 11:20 AM',relativeTime:'2d',category:'Follow-up',priority:78,unread:true,starred:false,summary:'Noah is waiting for your feedback on the API integration proposal sent last week.',actionRequired:'Review proposal and send an update',reason:'Sender is waiting; unanswered for two days',people:['Noah Williams','Aditya'],attachments:[],actionItems:[{task:'Review API integration proposal',owner:'You'},{task:'Send Noah a status update',deadline:'Today',owner:'You'}],threadCount:4,waitingDays:2},
{id:'e6',sender:'Dense Discovery',email:'hello@densediscovery.com',initials:'DD',subject:'Designing for a calmer internet',preview:'Issue 348: Humane interfaces, quiet software, and other things worth your attention.',body:'This week: humane interfaces, quiet software, and a selection of thoughtful links from around the web.',receivedAt:'Mon, 7:00 AM',relativeTime:'2d',category:'Newsletter',priority:18,unread:false,starred:false,summary:'A design newsletter covering humane interfaces and calm software.',actionRequired:'No action required',reason:'Newsletter with no direct request',people:['Dense Discovery'],attachments:[],actionItems:[],threadCount:1}
]
export const initialReminders:Reminder[]=[{id:'r1',emailId:'e5',title:'Follow up with Noah',when:'Tomorrow, 10:00 AM',status:'scheduled'}]

